// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG_dotnet.Data;

#nullable disable

namespace RPG_dotnet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250602215804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RPG_dotnet.Models.Ability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("characterId")
                        .HasColumnType("int");

                    b.Property<int>("damage")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("manaCost")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("characterId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Characters", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("baseDamage")
                        .HasColumnType("int");

                    b.Property<int>("defense")
                        .HasColumnType("int");

                    b.Property<int>("fighterClass")
                        .HasColumnType("int");

                    b.Property<int>("hitpoints")
                        .HasColumnType("int");

                    b.Property<int>("intelligence")
                        .HasColumnType("int");

                    b.Property<int>("mana")
                        .HasColumnType("int");

                    b.Property<int>("manaGainPerAttack")
                        .HasColumnType("int");

                    b.Property<int>("movement")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<int>("strength")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Loadout", b =>
                {
                    b.Property<int>("loadoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loadoutId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("loadoutId");

                    b.HasIndex("userId");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("RPG_dotnet.Models.LoadoutCharacter", b =>
                {
                    b.Property<int>("loadoutId")
                        .HasColumnType("int");

                    b.Property<int>("characterId")
                        .HasColumnType("int");

                    b.HasKey("loadoutId", "characterId");

                    b.HasIndex("characterId");

                    b.ToTable("LoadoutCharacter");
                });

            modelBuilder.Entity("RPG_dotnet.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Ability", b =>
                {
                    b.HasOne("RPG_dotnet.Models.Characters", "character")
                        .WithMany("abilities")
                        .HasForeignKey("characterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("character");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Loadout", b =>
                {
                    b.HasOne("RPG_dotnet.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("RPG_dotnet.Models.LoadoutCharacter", b =>
                {
                    b.HasOne("RPG_dotnet.Models.Characters", "character")
                        .WithMany()
                        .HasForeignKey("characterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_dotnet.Models.Loadout", "loadout")
                        .WithMany("characters")
                        .HasForeignKey("loadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("character");

                    b.Navigation("loadout");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Characters", b =>
                {
                    b.Navigation("abilities");
                });

            modelBuilder.Entity("RPG_dotnet.Models.Loadout", b =>
                {
                    b.Navigation("characters");
                });
#pragma warning restore 612, 618
        }
    }
}
